# Generated by Django 3.0 on 2022-04-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default=6789, max_length=10),
            preserve_default=False,
        ),
    ]
