# Generated by Django 3.0 on 2022-04-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('WAREHOUSE', 'warehouse'), ('RESIDENTIAL', 'residential'), ('COMMERICAL', 'commercial')], max_length=11)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
