# Generated by Django 3.0 on 2022-04-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_bin',
            old_name='fuflilled_date',
            new_name='fulfilled_date',
        ),
    ]
