# Generated by Django 3.0 on 2022-05-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220504_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='user_foreign_key',
            new_name='user',
        ),
    ]
