# Generated by Django 3.0 on 2022-04-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Route'),
        ),
    ]
