# Generated by Django 3.0 on 2022-05-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220504_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='bin_model_id',
            new_name='bin_model_foreign_key',
        ),
    ]
