# Generated by Django 3.0 on 2022-04-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220425_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.CharField(choices=[('PLASTIC', 'plastic'), ('METAL', 'metal')], max_length=7)),
                ('color', models.CharField(choices=[('FORREST-GREEN', 'forrest-green'), ('OLIVE-GREEN', 'olive-green'), ('SPRING-GREEN', 'spring-green')], max_length=14)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('volume_gallons', models.IntegerField()),
                ('weight_lbs', models.IntegerField()),
            ],
        ),
    ]
