# Generated by Django 3.0 on 2022-04-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bin_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField()),
                ('active', models.BooleanField()),
                ('bin_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bin_Model')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
    ]
