# Generated by Django 3.0 on 2022-04-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('fuflilled_date', models.DateField()),
                ('status', models.CharField(choices=[('PROCESSING', 'processing'), ('DELIVERED', 'delivered')], max_length=10)),
                ('bin_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bin_Model')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
    ]
